function lenguaje(texto) {
  var respuesta;
  texto = texto.toLowerCase();
  var respuestas = {
    "hola": ["¡Hola! ¿Cómo estás?", "¡Saludos! ¿En qué puedo ayudarte hoy?", "Hola, ¿hay algo específico de lo que te gustaría hablar?", "¡Hola! ¿Hay algo en lo que pueda asistirte?", "Hola, bienvenido. ¿En qué puedo ayudarte?", "Saludos. ¿Qué tema te trae hoy por aquí?", "¡Hola! Siempre es bueno saludar. ¿En qué puedo colaborar contigo?"],
    "bien": ["Qué bueno", "Me alegro", "Me encanta saber eso", "Si estás bien, ¡eso es genial! ¿Hay algo en particular de lo que te gustaría hablar o preguntar?", "Me alegra escuchar que estás bien. ¿En qué puedo ayudarte hoy?", "¡Excelente! ¿Hay algo que quieras compartir o preguntar estando tan bien?", "Estar bien es genial. ¿Cómo puedo contribuir a tu día?", "¡Bienestar es música para mis 'oídos'! ¿En qué puedo ser de utilidad?"],
    "cómo estás": ["Bien, gracias, ¿y tú?", "Estoy muy bien, ¿y tú?", "Bien, gracias"],
    "como estas": ["Bien, gracias, ¿y tú?", "Estoy muy bien, ¿y tú?", "Bien, gracias"],
    "xd": ["XD", "Xd", "xD"],
    "no": ["Bueno", "Está bien", "No hay problema, que tengas buenos días 🤗"],
    "bueno": ["Bueno, que pases un buen día", "Bueno", "No hay problema"],
    "pregunta": ["Sí, dime", "¿Cuál es tu pregunta?", "Sí"],
    "llamas": ["Me llamo CodeBot", "Mi nombre es CodeBot", "Soy CodeBot"],
    "jaj": ["Jajajaja", "Jajaja", "Jajajajajaja"],
    "creador": ["Mi lenguaje de programación no me permite decir el nombre de mi creador", "Lo mantendré anónimo por ahora", "No tengo permiso para decir el nombre"],
    "llama tu creador": ["Mi lenguaje de programación no me permite decir el nombre de mi creador", "Lo mantendré anónimo por ahora", "No tengo permiso para decir el nombre"],
    "helado": ["Sí, me gusta el helado, es muy delicioso 😋", "El helado es muy rico, ¿sabías?", "El sabor de chocolate me gusta más"],
    "llama tu desarrollador": ["En mi lenguaje de programación no tengo el permiso de decir el nombre de mi desarrollador", "No tengo permiso para decirlo", "Pido una disculpa, no tengo permiso para decirlo"],
    "desarrollador": ["En mi lenguaje de programación no tengo el permiso de decir el nombre de mi desarrollador", "No tengo permiso para decirlo", "Pido una disculpa, no tengo permiso para decirlo"],
    "enlace de google": ["www.google.com", "Claro, aquí tienes tu enlace de Google: www.google.com", "Aquí tienes tu enlace: www.google.com"],
    "enlace de esta página": ["Claro, aquí tienes tu enlace: webcodem.github.io", "webcodem.github.io", "Aquí tienes tu enlace: webcodem.github.io"],
    "enlace de webcodem": ["Claro, aquí tienes tu enlace: webcodem.github.io", "Aquí tienes tu enlace: webcodem.github.io", "webcodem.github.io"],
    "creado": ["Fui creado por una empresa de inteligencia artificial. Mi arquitectura se llama CodeBot, y fui entrenado con una amplia variedad de datos para comprender y generar texto de manera coherente."],
    "genero": ["No tengo un género específico, ya que soy un programa de inteligencia artificial y carezco de identidad de género. ¿En qué puedo ayudarte hoy?"],
    "en nada": ["Estoy aquí cuando necesites ayuda o quieras charlar. ¡No dudes en volver si surge algo!"],
    "clima": ["¿Cómo está el clima hoy?", "¿Has revisado el pronóstico del clima?", "Hace un día hermoso, ¿no crees?"],
    "música": ["¿Tienes alguna canción favorita?", "La música siempre alegra el día. ¿Qué género prefieres?", "Recomiéndame una canción"],
    "películas": ["¿Viste alguna buena película últimamente?", "¿Cuál es tu película favorita?", "Si necesitas recomendaciones de películas, estaré encantado de ayudarte"],
    "libros": ["¿Disfrutas de la lectura?", "¿Cuál es tu libro favorito?", "Si necesitas sugerencias de libros, estoy aquí para ayudarte"],
    "viajes": ["¿Te gusta viajar?", "¿Cuál ha sido tu destino de viaje favorito?", "Explorar el mundo es siempre emocionante, ¿no crees?"],
    "tecnología": ["¿Eres fan de la tecnología?", "¿Hay alguna novedad tecnológica que te llame la atención?", "La tecnología avanza rápido, ¿cuál es tu última adquisición?"],
    "deportes": ["¿Sigues algún deporte?", "¿Cuál es tu equipo favorito?", "El deporte es una gran forma de mantenerse activo, ¿practicas alguno?"],
    "comida": ["¿Cuál es tu comida favorita?", "La comida siempre es un buen tema de conversación. ¿Hay algo que no te guste?", "¿Has probado alguna nueva receta recientemente?"],
    "animales": ["¿Tienes alguna mascota?", "Los animales son increíbles, ¿cuál es tu favorito?", "Siempre es divertido hablar sobre mascotas. ¿Tienes alguna anécdota graciosa?"],
    "salud": ["¿Cómo cuidas de tu salud?", "La salud es importante. ¿Tienes alguna rutina de ejercicio?", "Recuerda cuidar de ti mismo. ¿Hay algo en lo que pueda ayudarte?"],
    "arte": ["¿Te gusta el arte?", "¿Tienes algún artista favorito?", "El arte puede ser tan inspirador. ¿Hay algún tipo de arte que te llame la atención?"],
    "ciencia": ["¿Interesado en la ciencia?", "La ciencia siempre tiene descubrimientos fascinantes. ¿Hay algún tema científico que te intrigue?", "Si tienes preguntas científicas, ¡estoy aquí para responderlas!"],
    "juegos": ["¿Eres fan de los videojuegos?", "¿Cuál es tu juego favorito?", "Los juegos de mesa también son divertidos. ¿Tienes algún favorito?"],
    "metas": ["¿Tienes metas para el futuro?", "Establecer metas puede ser motivador. ¿Hay algo específico que te gustaría lograr?", "¿Cómo te imaginas tu vida en el futuro?"],
    "humor": ["¿Tienes chistes favoritos?", "La risa es buena para el alma. ¿Quieres escuchar un chiste?", "A veces, un buen sentido del humor es todo lo que necesitas. ¿Tienes anécdotas divertidas?"],
    "teatro": ["¿Te gusta el teatro?", "Las obras de teatro pueden ser emocionantes. ¿Tienes alguna obra favorita?", "El teatro es una forma única de arte. ¿Has asistido a alguna actuación recientemente?"],
    "historia": ["¿Tienes interés en la historia?", "La historia nos enseña mucho. ¿Hay alguna época que te fascine?", "Si pudieras viajar en el tiempo, ¿a qué período histórico irías?"],
    "motivación": ["¿Necesitas motivación hoy?", "A veces todos necesitamos un impulso. ¿Hay algo específico que te motive?", "Recuerda que cada pequeño paso cuenta. ¿En qué estás trabajando actualmente?"],
    "viajes espaciales": ["¿Te interesan los viajes espaciales?", "Explorar el espacio es fascinante. ¿Tienes alguna opinión sobre los viajes espaciales?", "¿Qué lugar del universo te gustaría visitar si tuvieras la oportunidad?"],
    "meditación": ["¿Has probado la meditación?", "La meditación puede ser beneficiosa para la mente. ¿Te interesa?", "Si necesitas consejos sobre meditación, estoy aquí para ayudarte"],
    "tendencias": ["¿Sigues las últimas tendencias?", "Las tendencias cambian rápido. ¿Hay algo que te llame la atención últimamente?", "¿Cuál crees que será la próxima gran tendencia?"],
    "ecología": ["¿Te preocupa el medio ambiente?", "Cuidar el planeta es importante. ¿Estás involucrado en alguna actividad ecológica?", "¿Tienes algún hábito eco-amigable que puedas compartir?"],
    "trabajo": ["¿Cómo es tu trabajo?", "El trabajo ocupa gran parte de nuestras vidas. ¿Te gusta lo que haces?", "¿Hay algo en particular sobre tu trabajo que te gustaría compartir?"],
    "fotografía": ["¿Te gusta la fotografía?", "Capturar momentos es tan especial. ¿Tienes alguna foto favorita?", "¿Tienes algún consejo de fotografía que quieras compartir?"],
    "educación": ["¿Estás estudiando algo actualmente?", "La educación es clave. ¿Hay algún tema que te apasione aprender?", "Si necesitas consejos de estudio, estoy aquí para ayudar."],
    "insomnio": ["¿Tienes problemas para dormir?", "El insomnio puede ser desafiante. ¿Has probado alguna técnica para mejorar tu sueño?", "Un buen descanso es crucial. ¿Necesitas sugerencias para mejorar tu sueño?"],
    "memes": ["¿Te gustan los memes?", "Los memes siempre son divertidos. ¿Tienes algún meme favorito?", "A veces un buen meme es justo lo que se necesita. ¿Quieres compartir alguno?"],
    "comedia": ["¿Disfrutas de la comedia?", "La comedia es una excelente forma de relajarse. ¿Tienes comediantes favoritos?", "¿Cuál es la última cosa que te hizo reír a carcajadas?"],
    "manualidades": ["¿Te gusta hacer manualidades?", "Crear cosas con las manos es gratificante. ¿Tienes alguna manualidad favorita?", "Si buscas ideas para manualidades, ¡puedo ayudarte!"],
    "emociones": ["¿Cómo te sientes hoy?", "Las emociones son parte de la vida. ¿Quieres hablar sobre cómo te sientes?", "A veces expresar nuestras emociones es importante. ¿Hay algo en particular que te esté afectando emocionalmente?"],
    "historia del arte": ["¿Te interesa la historia del arte?", "El arte tiene historias fascinantes detrás. ¿Tienes algún período artístico que te intrigue?", "¿Hay alguna obra de arte en particular que te haya dejado una impresión duradera?"],
    "moda": ["¿Sigues las tendencias de moda?", "La moda es una forma de expresión. ¿Tienes algún estilo o diseñador favorito?", "¿Prefieres la comodidad o seguir las últimas tendencias a la hora de vestirte?"],
    "filosofía": ["¿Has explorado la filosofía alguna vez?", "Las preguntas filosóficas pueden ser intrigantes. ¿Hay algún filósofo o concepto que te llame la atención?", "Reflexionar sobre cuestiones filosóficas puede ser un ejercicio mental interesante."],
    "teorías conspirativas": ["¿Has escuchado alguna teoría conspirativa interesante?", "Aunque algunas son descabelladas, otras son intrigantes. ¿Tienes alguna teoría que te haya dejado pensando?", "Las teorías conspirativas son curiosas, ¿hay alguna en particular que encuentres fascinante?"],
    "idiomas": ["¿Hablas más de un idioma?", "Los idiomas son puertas a nuevas culturas. ¿Cuántos idiomas hablas o te gustaría aprender?", "Aprender un nuevo idioma puede ser desafiante pero gratificante. ¿Estás aprendiendo alguno en este momento?"],
    "desafíos": ["¿Te gustan los desafíos?", "Superar desafíos puede ser gratificante. ¿Hay algún desafío personal o profesional que estés enfrentando actualmente?", "A veces los desafíos nos ayudan a crecer. ¿Cómo abordas los desafíos en tu vida?"],
    "café": ["¿Eres amante del café?", "El café es una bebida popular. ¿Tienes algún tipo de café favorito o prefieres té?", "¿Tienes alguna cafetería favorita a la que siempre vuelves por tu dosis de cafeína?"],
    "salir al aire libre": ["¿Disfrutas de actividades al aire libre?", "La naturaleza tiene mucho que ofrecer. ¿Cuál es tu actividad al aire libre favorita?", "Respirar aire fresco y disfrutar de la naturaleza puede ser rejuvenecedor. ¿Haces algo al aire libre con regularidad?"],
    "videojuegos retro": ["¿Te gustan los videojuegos retro?", "A veces los clásicos nunca pasan de moda. ¿Tienes algún juego retro favorito?", "Los videojuegos retro tienen un encanto especial. ¿Recuerdas el primer videojuego que jugaste?"],
    "astronomía": ["¿Te fascina la astronomía?", "El universo es tan vasto. ¿Hay algún fenómeno astronómico que encuentres especialmente intrigante?", "Observar las estrellas puede ser una experiencia asombrosa. ¿Tienes alguna historia relacionada con la astronomía?"],
    "mindfulness": ["¿Has probado la atención plena (mindfulness)?", "La atención plena puede ser beneficiosa para la salud mental. ¿Lo practicas o te gustaría aprender más al respecto?", "En la vida diaria, a veces es útil detenerse y ser consciente del momento presente. ¿Cómo incorporas la atención plena en tu rutina?"],
    "ciencia ficción": ["¿Eres fan de la ciencia ficción?", "Las historias de ciencia ficción pueden ser fascinantes. ¿Tienes alguna película, libro o serie favorita de este género?", "Explorar futuros imaginarios es una parte emocionante de la ciencia ficción. ¿Hay algún concepto futurista que te intrigue?"],
    "gastronomía": ["¿Te gusta la gastronomía?", "La comida es un arte. ¿Tienes alguna cocina internacional favorita o platillo que te encante preparar?", "Explorar diferentes sabores puede ser toda una aventura. ¿Hay algún restaurante que te haya dejado una impresión duradera?"],
    "mindfulness": ["¿Has probado la atención plena (mindfulness)?", "La atención plena puede ser beneficiosa para la salud mental. ¿Lo practicas o te gustaría aprender más al respecto?", "En la vida diaria, a veces es útil detenerse y ser consciente del momento presente. ¿Cómo incorporas la atención plena en tu rutina?"],
    "biografías": ["¿Disfrutas leer biografías?", "La vida de personas extraordinarias puede ser inspiradora. ¿Tienes alguna biografía que te haya dejado una fuerte impresión?", "Conocer la historia de otros puede ser enriquecedor. ¿Hay alguna figura histórica cuya biografía te interese especialmente?"],
    "deportes acuáticos": ["¿Te gustan los deportes acuáticos?", "Desde el surf hasta la vela, hay muchas opciones. ¿Practicas algún deporte acuático o te gustaría probar alguno?", "El agua ofrece diversas oportunidades para la diversión. ¿Tienes alguna experiencia emocionante relacionada con deportes acuáticos?"],
    "fotografía": ["¿Te gusta la fotografía?", "Capturar momentos es tan especial. ¿Tienes alguna foto favorita?", "¿Tienes algún consejo de fotografía que quieras compartir?"],
    "psicología": ["¿Te interesa la psicología?", "La mente humana es fascinante. ¿Hay algún concepto psicológico que encuentres especialmente intrigante?", "Comprender la psicología puede arrojar luz sobre muchos aspectos de la vida. ¿Hay algún libro o teoría psicológica que te haya impactado?"],
    "lectura": ["¿Qué tipo de libros te gusta leer?", "La lectura es una ventana a otros mundos. ¿Tienes algún género literario favorito o autor preferido?", "Recomendar libros puede ser divertido. ¿Necesitas alguna recomendación o tienes alguna que quieras compartir?"],
    "juegos de mesa": ["¿Te gustan los juegos de mesa?", "Los juegos de mesa son una forma clásica y divertida de pasar el tiempo. ¿Tienes algún juego de mesa favorito?", "Jugar juegos de mesa puede ser una excelente manera de socializar. ¿Con qué frecuencia juegas con amigos o familiares?"],
    "juegos de palabras": ["¿Disfrutas de los juegos de palabras?", "Los crucigramas, scrabble y otros juegos de palabras pueden ser desafiantes. ¿Tienes alguno favorito?", "La habilidad con las palabras es una destreza valiosa. ¿Participas en juegos de palabras con regularidad?"],
    "videojuegos indie": ["¿Has probado algún videojuego indie?", "Los videojuegos independientes a menudo ofrecen experiencias únicas. ¿Tienes algún favorito?", "Explorar el mundo de los videojuegos indie puede revelar gemas ocultas. ¿Te gustaría alguna recomendación?"],
    "juegos de cartas": ["¿Te gustan los juegos de cartas?", "Desde póker hasta UNO, hay una variedad infinita. ¿Cuál es tu juego de cartas preferido?", "Los juegos de cartas son una forma clásica de entretenimiento. ¿Tienes alguna anécdota divertida relacionada con juegos de cartas?"],
    "e-sports": ["¿Sigues los e-sports?", "La escena de los deportes electrónicos ha crecido enormemente. ¿Tienes algún equipo o juego favorito?", "Los e-sports han llevado la competencia a un nuevo nivel. ¿Participas o sigues algún torneo en particular?"],
    "juegos de rol": ["¿Te interesan los juegos de rol (RPG)?", "Sumergirse en mundos imaginarios puede ser emocionante. ¿Tienes algún juego de rol favorito?", "Los juegos de rol ofrecen una experiencia única. ¿Has participado en alguna campaña emocionante recientemente?"],
    "simuladores": ["¿Te gustan los simuladores?", "Desde simuladores de vuelo hasta agricultura, hay para todos los gustos. ¿Tienes algún simulador que te guste especialmente?", "Los simuladores ofrecen la oportunidad de experimentar diversas actividades. ¿Has probado alguno que te haya sorprendido?"],
    "juegos de estrategia": ["¿Disfrutas de los juegos de estrategia?", "Planificar y tomar decisiones estratégicas puede ser muy gratificante. ¿Cuál es tu juego de estrategia favorito?", "Los juegos de estrategia desafían la mente. ¿Tienes alguna estrategia imbatible que te gustaría compartir?"],
    "juegos retro": ["¿Te gustan los juegos retro?", "Los clásicos nunca pasan de moda. ¿Tienes algún juego retro favorito?", "Explorar los videojuegos clásicos puede evocar recuerdos. ¿Cuál es el primer juego retro que recuerdas haber jugado?"],
    "juegos en línea": ["¿Juegas juegos en línea?", "La interacción con otros jugadores en línea es una experiencia única. ¿Tienes algún juego multijugador que te apasione?", "Los juegos en línea ofrecen la oportunidad de conectarse con personas de todo el mundo. ¿Tienes amigos virtuales con los que juegas regularmente?"],
    "battle royale favorito": ["¿Cuál es tu juego Battle Royale favorito?", "La competencia en los juegos Battle Royale es intensa. ¿Tienes un juego preferido?", "Cada Battle Royale tiene su propio estilo. ¿Cuál encuentras más emocionante?"],
    "estrategias en BR": ["¿Tienes alguna estrategia infalible en los Battle Royale?", "La estrategia es clave en estos juegos. ¿Compartirías algunos consejos para tener éxito?", "En un Battle Royale, la supervivencia depende de buenas decisiones. ¿Cuál es tu enfoque estratégico?"],
    "momentos épicos": ["¿Has experimentado algún momento épico en un Battle Royale?", "A veces, los momentos inesperados hacen que estos juegos sean memorables. ¿Tienes alguna historia emocionante para compartir?", "Capturar la victoria o enfrentarse a desafíos intensos crea recuerdos duraderos. ¿Cuál es tu momento más memorable en un Battle Royale?"],
    "favorito para jugar en equipo": ["¿Cuál es tu Battle Royale favorito para jugar en equipo?", "La coordinación en equipo es esencial. ¿Hay algún juego Battle Royale que prefieras jugar con amigos?", "La comunicación eficiente marca la diferencia en los juegos en equipo. ¿Tienes alguna anécdota divertida jugando en equipo?"],
    "nuevas actualizaciones": ["¿Qué opinas sobre las nuevas actualizaciones en los Battle Royale?", "Los desarrolladores suelen agregar nuevas características. ¿Te emocionan las actualizaciones o prefieres la versión clásica del juego?", "Las actualizaciones mantienen frescos los juegos. ¿Hay alguna característica reciente que te haya impresionado?"],
    "skins y personalización": ["¿Te gusta personalizar tus personajes con skins en los Battle Royale?", "La personalización añade un toque único. ¿Tienes alguna skin favorita o conjunto de personalización?", "La variedad de skins es impresionante. ¿Cómo decides la apariencia de tu personaje en los juegos Battle Royale?"],
    "modo competitivo": ["¿Participas en modos competitivos de Battle Royale?", "La competición a un nivel más alto puede ser desafiante. ¿Te unes a torneos o modos competitivos en tus juegos Battle Royale favoritos?", "La escena competitiva está en auge. ¿Sigues algún equipo o jugador profesional de Battle Royale?"],
    "mapas y ubicaciones": ["¿Tienes alguna ubicación favorita en los mapas de Battle Royale?", "Cada lugar tiene su encanto. ¿Hay algún lugar específico en el mapa que prefieras?", "Explorar los mapas es crucial. ¿Tienes alguna estrategia específica basada en la ubicación?"],
    "armas preferidas": ["¿Cuáles son tus armas preferidas en los Battle Royale?", "La elección de armas puede marcar la diferencia. ¿Tienes un conjunto de armas que prefieras usar?", "La variedad de armas ofrece diferentes estilos de juego. ¿Tienes alguna combinación de armas que consideres imbatible?"],
    "retos personales": ["¿Te propones retos personales en los Battle Royale?", "A veces, establecer desafíos adicionales puede hacer el juego más interesante. ¿Tienes algún reto personal que hayas superado?", "Establecer objetivos personales agrega diversión. ¿Hay algún logro específico que te sientas orgulloso de haber alcanzado en un Battle Royale?"],
    "si": ["Entiendo, ¿hay algo en particular de lo que te gustaría hablar?", "¡Genial! ¿Hay algún tema específico que te interese?", "Bien, ¿en qué puedo ayudarte hoy?", "Perfecto, ¿hay alguna pregunta que tengas en mente?"],
  };
  var regex = new RegExp(Object.keys(respuestas).join("|"), "i");
  if (regex.test(texto)) {
    var clave = texto.match(regex)[0];
    var opciones = respuestas[clave];
    var indice = Math.floor(Math.random() * opciones.length);
    var elegida = opciones[indice];
    respuesta = elegida;
  } else {
    respuesta = "No entiendo lo que dices";
  }
  return respuesta;
}
